#!/usr/bin/python

import sys, os
import logging
from PyQt5.QtWidgets import QApplication, QMessageBox

USER = os.getlogin() 

# This defines the default path to the top dir of a tree 
# containing "source" files. These files are scanned into a list
# so the user can browse them and copy to "destination" dirs.
DEFAULT_SRC_FILES_PATH = str('/media/'+USER+'/c8f652a8-72b3-4877-88ef-7710a646841d/recovered/recup_dir.215')
#print('DEFAULT_SRC_FILES_PATH:',DEFAULT_SRC_FILES_PATH)
# This defines the default path to a dir (outside of the "source" file 
# tree), which contains one level of subdirs. These subdirs are the 
# "destination" for copy/move operations from "source" files. 
DEFAULT_DST_FILES_PATH = str('/media/'+USER+'/c8f652a8-72b3-4877-88ef-7710a646841d/pics')
# path to icon files 
# TODO: compile icons to resource
DEFAULT_ICON_FILES_PATH = 'res/'

#image file formats supported by Pillow
#TODO: implement filters
DEFAULT_SUPPORTED_IMAGE_FORMATS = [ 
    #format     #mime type                  #filter
    ( 'BMP'     , 'image/bmp'               , False ),
    ( 'BUFR'    , ''                        , False ),
    ( 'DDS'     , ''                        , False ),
    ( 'DIB'     , 'image/bmp'               , False ),
    ( 'EPS'     , 'application/postscript'  , False ),
    ( 'FITS'    , ''                        , False ),
    ( 'GIF'     , 'image/gif'               , False ),
    ( 'GRIB'    , ''                        , False ),
    ( 'HDF5'    , ''                        , False ),
    ( 'ICNS'    , 'image/icns'              , False ),
    ( 'ICO'     , 'image/x-icon'            , False ),
    ( 'IM'      , ''                        , False ),
    ( 'JPEG'    , 'image/jpeg'              , False ),
    ( 'JPEG2000', 'image/jp2'               , False ),
    ( 'MPEG'    , 'video/mpeg'              , False ),
    ( 'MSP'     , ''                        , False ),
    ( 'PCX'     , 'image/x-pcx'             , False ),
    ( 'PNG'     , 'image/png'               , False ),
    ( 'PPM'     , 'image/x-portable-anymap' , False ),
    ( 'SGI'     , 'image/sgi'               , False ),
    ( 'SPIDER'  , ''                        , False ),
    ( 'TGA'     , 'image/x-tga'             , False ),
    ( 'TIFF'    , 'image/tiff'              , False ),
    ( 'WEBP'    , 'image/webp'              , False ),
    ( 'WMF'     , 'windows media file'      , False ),
    ( 'XBM'     , 'image/xbm'               , False ),
]

# file types recovered by photorec
DEFAULT_PHOTOREC_FILE_FORMATS = [
    #ext            #description                            #filter
#Archive
    ( '7z'          , '7-Zip archive file'                  , False ),
    ( 'a'           , 'Unix/Linux archive'                  , False ),
    ( 'ace'         , 'ACE Archive'                         , False ),
    ( 'apk'         , 'Android Package Kit'                 , False ),
    ( 'arj'         , 'Archive'                             , False ),
    ( 'bkf'         , 'MS Backup file'                      , False ),
    ( 'bz2'         , 'bzip2 compressed data'               , False ),
    ( 'cab'         , 'MS cabinet archive'                  , False ),
    ( 'dar'         , 'dar3 archive'                        , False ),
    ( 'deb'         , 'Debian Archive'                      , False ),
    ( 'dump'        , 'Dump/Restore Archive'                , False ),
    ( 'ghx'         , 'Grasshopper archive'                 , False ),
    ( 'gz'          , 'gzip compressed data'                , False ),
    ( 'lzh'         , 'lzh/LArc archive'                    , False ),
    ( 'lzo'         , 'LZO archive'                         , False ),
    ( 'par2'        , 'archive'                             , False ),
    ( 'rar'         , 'Rar archive'                         , False ),
    ( 'rpm'         , 'RPM package'                         , False ),
    ( 'stu'         , 'StuffIt Archive'                     , False ),
    ( 'tar'         , 'tar archive'                         , False ),
    ( 'tar.gz'      , 'compressed tar archive'              , False ),
    ( 'vbm'         , 'Veeam Backup Metadata'               , False ),
    ( 'wim'         , 'Windows imaging (WIM) image'         , False ),
    ( 'xar'         , 'xar archive'                         , False ),
    ( 'xz'          , 'xz Archive'                          , False ),
    ( 'zip'         , 'zip archive'                         , False ),
    #MultimediaFalse
    ( '3ds'         , 'max'                                 , False ),
    ( '3dm'         , 'Rhino / openNURBS'                   , False ),
    ( '3g2'         , 'Video for 3G mobile phone (CDMA)'    , False ),
    ( '3gp'         , 'Video for 3G mobile phone (GSM)'     , False ),
    ( 'abr'         , 'Adobe Brush'                         , False ),
    ( 'acb'         , 'Adobe Color Book'                    , False ),
    ( 'ado'         , 'Adobe Duotone Options'               , False ),
    ( 'aep'         , 'After Effects'                       , False ),
    ( 'afdesign'    , 'afdesign'                            , False ),
    ( 'aif'         , 'Apple Audio'                         , False ),
    ( 'albm'        , 'HP Photosmart Photo Printing Album'  , False ),
    ( 'all'         , 'Cubase Song format'                  , False ),
    ( 'als'         , 'Ableton Live Sets'                   , False ),
    ( 'ani'         , 'Windows Animated Cursor'             , False ),
    ( 'ape'         , 'Monkey Audio compressed format'      , False ),
    ( 'ari'         , 'ARRI Raw Video'                      , False ),
    ( 'arw'         , 'Sony raw image (TIFF image)'         , False ),
    ( 'asf'         , 'Advanced Streaming Format'           , False ),
    ( 'wma'         , 'Windows Media Audio'                 , False ),
    ( 'wmv'         , 'Windows Media Video'                 , False ),
    ( 'asl'         , 'Adobe Layer Style'                   , False ),
    ( 'au'          , 'Sun/NeXT audio data'                 , False ),
    ( 'avi'         , 'RIFF video'                          , False ),
    ( 'axp'         , 'Pinnacle Studio'                     , False ),
    ( 'binvox'      , 'Binvox Voxel File'                   , False ),
    ( 'bdm'         , 'AVHCD index'                         , False ),
    ( 'bld'         , 'blender'                             , False ),
    ( 'blend'       , 'Blender'                             , False ),
    ( 'bmp'         , 'BMP bitmap image'                    , False ),
    ( 'bpg'         , 'Better Portable Graphics image'      , False ),
    ( 'bvr'         , 'Blue Iris DVR'                       , False ),
    ( 'c4d'         , 'Cinema 4d'                           , False ),
    ( 'caf'         , 'Core Audio Format'                   , False ),
    ( 'cam'         , 'Image'                               , False ),
    ( 'camrec'      , 'Camtasia Camrec'                     , False ),
    ( 'CATDrawing'  , 'CATIA'                               , False ),
    ( 'cda'         , 'CD Audio'                            , False ),
    ( 'cdd'         , 'Concept Draw Document'               , False ),
    ( 'cdl'         , 'Concept Draw Library'                , False ),
    ( 'cdr'         , 'Corel Draw (RIFF)'                   , False ),
    ( 'cdt'         , 'Concept Draw Template'               , False ),
    ( 'celtx'       , 'Celtx'                               , False ),
    ( 'che'         , 'Compucon EOS Design File'            , False ),
    ( 'comicdoc'    , 'Comic Life'                          , False ),
    ( 'cpi'         , 'AVCHD Clip Information'              , False ),
    ( 'cpr'         , 'Cubase Project File'                 , False ),
    ( 'cr2'         , 'Canon Raw 2 picture (TIFF image)'    , False ),
    ( 'cr3'         , 'Canon Raw v3 (MOV family)'           , False ),
    ( 'crw'         , 'Canon Raw picture'                   , False ),
    ( 'csh'         , 'Adobe Custom shapes'                 , False ),
    ( 'ctg'         , 'Canon catalog'                       , False ),
    ( 'cue'         , 'Cue sheet'                           , False ),
    ( 'dad'         , 'Micae DVR'                           , False ),
    ( 'db'          , 'Thumbs.db'                           , False ),
    ( 'dcm'         , 'DICOM'                               , False ),
    ( 'dcr'         , 'Kodak Raw picture (TIFF image)'      , False ),
    ( 'djv'         , 'DjVu'                                , False ),
    ( 'dng'         , 'Adobe Digital Negative'              , False ),
    ( 'dp'          , 'Photobook Designer Software'         , False ),
    ( 'dpx'         , 'Cineon image file/SMTPE DPX'         , False ),
    ( 'ds2'         , 'Digital Speech Standard v2'          , False ),
    ( 'dsc'         , 'Nikon DSC'                           , False ),
    ( 'dss'         , 'Digital Speech Standard'             , False ),
    ( 'ds_store'    , 'Apple indexing file'                 , False ),
    ( 'dta'         , 'SPSS'                                , False ),
    ( 'dv'          , 'DIF Digital Video'                   , False ),
    ( 'dvi'         , 'TeX DVI'                             , False ),
    ( 'dvr'         , 'RT60'                                , False ),
    ( 'dwg'         , 'AutoCAD'                             , False ),
    ( 'emf'         , 'Windows Enhanced MetaFile'           , False ),
    ( 'epub'        , 'Electronic Publication'              , False ),
    ( 'ers'         , 'ER Mapper Rasters'                   , False ),
    ( 'exs'         , 'Apple Logic'                         , False ),
    ( 'fcp'         , 'Final Cut Pro'                       , False ),
    ( 'fh10'        , 'Macromedia Freehand 10'              , False ),
    ( 'fh5'         , 'Macromedia Freehand 5'               , False ),
    ( 'flac'        , 'Free Lossless Audio Codec'           , False ),
    ( 'fla'         , 'Flash Project File'                  , False ),
    ( 'flp'         , 'Fruity Loop'                         , False ),
    ( 'flv'         , 'Macromedia'                          , False ),
    ( 'gi'          , 'Roxio Creator'                       , False ),
    ( 'gif'         , 'Graphic Interchange Format'          , False ),
    ( 'gp4'         , 'Guitar Pro 4'                        , False ),
    ( 'gp5'         , 'Guitar Pro 5'                        , False ),
    ( 'gpx'         , 'Guitar Pro 6'                        , False ),
    ( 'gsm'         , 'Group Speciale Mobile GSM 06.10'     , False ),
    ( 'heic'        , 'High Efficiency Image File'          , False ),
    ( 'icc'         , 'Color profiles'                      , False ),
    ( 'icns'        , 'Apple Icon Image'                    , False ),
    ( 'ico'         , 'Windows Icon'                        , False ),
    ( 'idf'         , 'MIDI Instruments Definition File'    , False ),
    ( 'idx'         , 'RT60'                                , False ),
    ( 'iff'         , 'Audio Interchange File Format'       , False ),
    ( 'ind'         , 'InDesign File'                       , False ),
    ( 'ifo'         , 'DVD Video manager or title set'      , False ),
    ( 'indd'        , 'Macromedia InDesign'                 , False ),
    ( 'info'        , 'ZoomBrowser Thumbnail info'          , False ),
    ( 'ipt'         , 'Autodesk Inventor part file'         , False ),
    ( 'iso'         , 'CD/DVD iso image (ISO0660)'          , False ),
    ( 'it'          , 'Impulse Tracker'                     , False ),
    ( 'itu'         , 'iTunes'                              , False ),
    ( 'ora'         , 'Mypaint .ora'                        , False ),
    ( 'jng'         , 'JPEG Network Graphics'               , False ),
    ( 'jpg'         , 'JPEG 2000'                           , False ),
    ( 'jpg'         , 'JPEG picture'                        , False ),
    ( 'kra'         , 'Krita'                               , False ),
    ( 'logic'       , 'Apple Logic Studio'                  , False ),
    ( 'm2t'         , 'Blu-ray MPEG-2'                      , False ),
    ( 'm2ts'        , 'Blu-ray MPEG-2'                      , False ),
    ( 'm3u'         , 'MPEG Audio Layer 3 URL'              , False ),
    ( 'm4p'         , 'MPEG-4 Audio'                        , False ),
    ( 'max'         , '3ds'                                 , False ),
    ( 'max'         , 'Paperport'                           , False ),
    ( 'mb'          , 'Maya'                                , False ),
    ( 'mcf'         , 'Fotobook'                            , False ),
    ( 'mfa'         , 'Games Factory Multimedia Fusion'     , False ),
    ( 'mhbd'        , 'iTunes'                              , False ),
    ( 'mid'         , 'MIDI'                                , False ),
    ( 'mkv'         , 'Matroska'                            , False ),
    ( 'mlv'         , 'Magic Lantern Video'                 , False ),
    ( 'mng'         , 'Multiple-Image Network Graphics'     , False ),
    ( 'mov'         , 'Quicktime Movie'                     , False ),
    ( 'mp'          , 'Maya'                                , False ),
    ( 'mp3'         , 'MPEG ADTS, layer III, v1 audio'      , False ),
    ( 'mp4'         , 'MPEG 4'                              , False ),
    ( 'mpg'         , 'MPEG video'                          , False ),
    ( 'mpl'         , 'AVHCD playlist'                      , False ),
    ( 'mpo'         , 'Multi-picture format'                , False ),
    ( 'mrw'         , 'Minolta Raw picture'                 , False ),
    ( 'mus'         , 'Finale Music Score'                  , False ),
    ( 'mws'         , 'MetaStock'                           , False ),
    ( 'nef'         , 'Nikon Raw picture (TIFF image)'      , False ),
    ( 'oci'         , 'OpenCanvas Image .oci'               , False ),
    ( 'ogg'         , 'OGG Vorbis audio'                    , False ),
    ( 'ogm'         , 'OGG audio'                           , False ),
    ( 'ogv'         , 'Ogg data, Theora video'              , False ),
    ( 'orf'         , 'Olympus Raw Format picture'          , False ),
    ( 'pbm'         , 'Portable Bitmap'                     , False ),
    ( 'pct'         , 'Macintosh Picture'                   , False ),
    ( 'pcx'         , 'PCX file format'                     , False ),
    ( 'psb'         , 'Adobe Photoshop Image'               , False ),
    ( 'pef'         , 'Pentax Raw picture (TIFF image)'     , False ),
    ( 'pgm'         , 'Portable GrayMap'                    , False ),
    ( 'png'         , 'Portable Network Graphics'           , False ),
    ( 'pnm'         , 'Portable anymap'                     , False ),
    ( 'ppm'         , 'Portable PixMap'                     , False ),
    ( 'prproj'      , 'Adobe Premiere project'              , False ),
    ( 'psd'         , 'Adobe Photoshop Image'               , False ),
    ( 'psf'         , 'Print Shop File'                     , False ),
    ( 'psp'         , 'Paint Shop Pro Image File'           , False ),
    ( 'ptb'         , 'PowerTab'                            , False ),
    ( 'pts'         , 'PTGui panoramic stitching'           , False ),
    ( 'pvp'         , 'Php Video Pro'                       , False ),
    ( 'qcp'         , 'QCP Speech Data (RFC3625)'           , False ),
    ( 'qkt'         , 'Apple QuickTake 100'                 , False ),
    ( 'qxd'         , 'QuarkXpress Document'                , False ),
    ( 'qxp'         , 'QuarkXpress Document'                , False ),
    ( 'r3d'         , 'RED r3d camera'                      , False ),
    ( 'raf'         , 'Raw Fujifilm picture'                , False ),
    ( 'ram'         , 'Real Media'                          , False ),
    ( 'ra'          , 'Real Audio'                          , False ),
    ( 'raw'         , 'Contax/Panasonic/Leica picture'      , False ),
    ( 'rdc'         , 'Rollei picture'                      , False ),
    ( 'rm'          , 'Real Media'                          , False ),
    ( 'rns'         , 'Reason'                              , False ),
    ( 'rns'         , 'Reason Audio File'                   , False ),
    ( 'rpp'         , 'Reaper Project'                      , False ),
    ( 'rw2'         , 'Panasonic Raw 2'                     , False ),
    ( 'rx2'         , 'Zotope RX 2, Audio Repair file'      , False ),
    ( 'ses'         , 'Cool Edit/Adobe Audition session'    , False ),
    ( 'shn'         , 'Shorten audio file'                  , False ),
    ( 'sib'         , 'Sibelius'                            , False ),
    ( 'sit'         , 'Mikron'                              , False ),
    ( 'skd'         , 'AutoSketch drawing'                  , False ),
    ( 'sketch'      , 'Vector graphics file by Sketch'      , False ),
    ( 'smil'        , 'Synchronized MM Integration Lang'    , False ),
    ( 'spss'        , 'SPSS'                                , False ),
    ( 'sr2'         , 'Sony Raw picture (TIFF image)'       , False ),
    ( 'svg'         , 'Scalable Vector Graphics'            , False ),
    ( 'swc'         , 'Macromedia Compressed Flash'         , False ),
    ( 'swf'         , 'MacroMedia Flash (Compiled)'         , False ),
    ( 'tg'          , 'Tux Guitar 1.2'                      , False ),
    ( 'tif'         , 'Tag Image File Format'               , False ),
    ( 'TiVo'        , 'video record'                        , False ),
    ( 'tod'         , 'Blu-ray MPEG-2'                      , False ),
    ( 'tpl'         , 'Adobe Tool Preset'                   , False ),
    ( 'ts'          , 'MPEG-2 Transport Stream'             , False ),
    ( 'vdj'         , 'VirtualDJ'                           , False ),
    ( 'wav'         , 'RIFF audio'                          , False ),
    ( 'wdp'         , 'JPEG XR'                             , False ),
    ( 'webm'        , 'Matroska'                            , False ),
    ( 'webp'        , 'WebP Image Format'                   , False ),
    ( 'wee'         , 'weecast'                             , False ),
    ( 'wmf'         , 'Windows Metafile'                    , False ),
    ( 'wnk'         , 'Wink screen capture'                 , False ),
    ( 'wpb'         , 'OpenCanvas files'                    , False ),
    ( 'wpl'         , 'Windows Play List'                   , False ),
    ( 'wtv'         , 'Windows Media Center TV'             , False ),
    ( 'wv'          , 'WavPack Compressor'                  , False ),
    ( 'x3f'         , 'Sigma/Foveon X3 raw picture'         , False ),
    ( 'x3i'         , 'Sigma/Foveon X3 raw picture'         , False ),
    ( 'xcf'         , 'GIMP XCF File'                       , False ),
    ( 'xd'          , 'Adobe xd'                            , False ),
    ( 'xm'          , 'FastTrackerII Extended Module'       , False ),
    ( 'xmp'         , 'Adobe Extensible Metadata Platform'  , False ),
    ( 'xrns'        , 'Extended Renoise song file'          , False ),
    ( 'xv'          , 'XV thumbnail image'                  , False ),
    ( 'zcode'       , 'Zortrax 3D printing'                 , False ),
    #Office
    ('accdb'        , 'Microsoft Access database'           , False ),
    ('ai'           , 'Adobe Illustrator'                   , False ),
    ('apr'          , 'Lotus Approach'                      , False ),
    ('csv'          , 'Comma separated values'              , False ),
    ('cwk'          , 'AppleWorks'                          , False ),
    ('doc'          , 'Microsoft Word (OLE document)'       , False ),
    ('docx'         , 'Microsoft Office OpenXML (ZIP)'      , False ),
    ('et'           , 'Microsoft Excel'                     , False ),
    ('fb2'          , 'FictionBook'                         , False ),
    ('fods'         , 'OpenDocument Flat XML Spreadsheet'   , False ),
    ('fp7'          , 'File Maker Pro 7'                    , False ),
    ('fp12'         , 'File Maker Pro 12'                   , False ),
    ('gnucash'      , 'GnuCash,'                            , False ),
    ('kmy'          , 'KMyMoney (gz file family)'           , False ),
    ('lyx'          , 'LyX'                                 , False ),
    ('mdb'          , 'Microsoft Access database'           , False ),
    ('njx'          , 'NJStar'                              , False ),
    ('odg'          , 'OpenDocument Graphics (ZIP)'         , False ),
    ('odp'          , 'OpenDocument Presentation (ZIP)'     , False ),
    ('ods'          , 'OpenDocument Spreadsheet (ZIP)'      , False ),
    ('odt'          , 'OpenDocument Text (ZIP)'             , False ),
    ('one'          , 'Microsoft OneNote'                   , False ),
    ('pages'        , 'iWork'                               , False ),
    ('pap'          , 'Papyrus word file'                   , False ),
    ('ppt'          , 'PowerPoint presentation'             , False ),
    ('pptx'         , 'Microsoft Office "Open" XML (ZIP)'   , False ),
    ('pub'          , 'Microsoft Publisher'                 , False ),
    ('qbb'          , 'Quickbooks Backup'                   , False ),
    ('qbw'          , 'Quickbooks - Company File'           , False ),
    ('qpw'          , 'Quattro Pro spreadsheet'             , False ),
    ('rtf'          , 'Rich Text Format'                    , False ),
    ('sda'          , 'StarDraw (OLE document)'             , False ),
    ('sdc'          , 'StarCalc (OLE document)'             , False ),
    ('sdd'          , 'StarImpress (OLE document)'          , False ),
    ('sdw'          , 'StarWriter (OLE document)'           , False ),
    ('slk'          , 'Sylk, Multiplan Symbolic Link'       , False ),
    ('sav'          , 'SPSS saved data'                     , False ),
    ('snt'          , 'Windows Sticky Notes'                , False ),
    ('sxc'          , 'OpenOffice Spreadsheet (ZIP)'        , False ),
    ('sxd'          , 'OpenOffice Drawing (ZIP)'            , False ),
    ('sxi'          , 'OpenOffice Presentation (ZIP)'       , False ),
    ('sxw'          , 'OpenOffice Text Document (ZIP)'      , False ),
    ('tex'          , 'LaTeX (Text file family)'            , False ),
    ('txt'          , 'Text file'                           , False ),
    ('vsd'          , 'Visio document (OLE document)'       , False ),
    ('vsdx'         , 'Microsoft Visio 2010+'               , False ),
    ('wpd'          , 'Corel Documents'                     , False ),
    ('wps'          , 'Microsoft Works (Ole document'       , False ),
    ('xlr'          , 'Microsoft Works Spreadsheet/Chart'   , False ),
    ('xls'          , 'Microsoft Excel'                     , False ),
    ('xlsx'         , 'Microsoft Office OpenXML'            , False ),
    ('wdb'          , 'Microsoft Works Database'            , False ),
    ('wk4'          , 'Lotus 1-2-3 v4'                      , False ),
    ('wks'          , 'Lotus 1-2-3 v5'                      , False ),
    #Others       
    ( '1cd'         , 'Russian Finance 1C:Enterprise 8'     , False ),
    ( 'ab'          , 'Mac Address Book'                    , False ),
    ( 'adr'         , 'Opera Hotlist'                       , False ),
    ( 'agn'         , 'Autogen'                             , False ),
    ( 'ahn'         , 'Ahnenblatt'                          , False ),
    ( 'amb'         , 'Licom AlphaCAM'                      , False ),
    ( 'amd'         , 'AlphaCAM'                            , False ),
    ( 'amr'         , 'Adaptive Multi-Rate'                 , False ),
    ( 'amt'         , 'AlphaCAM'                            , False ),
    ( 'apa'         , 'APA Style Helper'                    , False ),
    ( 'apple'       , 'AppleSingle/AppleDouble'             , False ),
    ( 'asm'         , 'Pro/ENGINEER Assembly'               , False ),
    ( 'asp'         , 'ASP script'                          , False ),
    ( 'atd'         , 'Agelong Tree Database'               , False ),
    ( 'atd'         , 'AlphaCAM'                            , False ),
    ( 'att'         , 'AlphaCAM'                            , False ),
    ( 'axx'         , 'AxCrypt'                             , False ),
    ( 'bac'         , 'Bacula backup'                       , False ),
    ( 'bai'         , 'SAM/BAM sequencing file formats'     , False ),
    ( 'bam'         , 'SAM/BAM sequencing file formats'     , False ),
    ( 'bat'         , 'Dos/Windows Batch'                   , False ),
    ( 'bgz'         , 'SAM/BAM sequencing file formats'     , False ),
    ( 'bim'         , 'Broadcast Interface Module'          , False ),
    ( 'c'           , 'C programming language'              , False ),
    ( 'chm'         , 'Microsoft Windows HtmlHelp Data'     , False ),
    ( 'class'       , 'Java Class'                          , False ),
    ( 'cls'         , 'Microsoft VB'                        , False ),
    ( 'cm'          , 'Comic Life'                          , False ),
    ( 'compress'    , 'MS compress file (SZDD)'             , False ),
    ( 'cow'         , 'Qemu Image'                          , False ),
    ( 'cp_'         , 'MS compress file (SZDD)'             , False ),
    ( 'csi'         , 'SAM/BAM sequencing file formats'     , False ),
    ( 'd2s'         , 'Diablo II'                           , False ),
    ( 'dat'         , 'Internet Explorer index.dat'         , False ),
    ( 'dbf'         , 'DBase 3 (prone to false positive)'   , False ),
    ( 'dbn'         , 'DriftBox'                            , False ),
    ( 'dbx'         , 'Outlook Express'                     , False ),
    ( 'dc'          , 'TSCe Survey Controller DC v10.0'     , False ),
    ( 'ddf'         , 'Didson Data File (v3 and v4)'        , False ),
    ( 'dex'         , 'Dalvik'                              , False ),
    ( 'dgn'         , 'MicroStation CAD file format'        , False ),
    ( 'dif'         , 'Lotus Data Interchange Format'       , False ),
    ( 'dim'         , 'SunPCI Disk Image'                   , False ),
    ( 'diskimage'   , 'SunPCI Disk Image'                   , False ),
    ( 'dll'         , 'Microsoft Dynamic Link Library'      , False ),
    ( 'dmp'         , 'Oracle Dump (export)'                , False ),
    ( 'drw'         , 'Pro/ENGINEER Drawing'                , False ),
    ( 'dsa'         , 'SSH DSA private key'                 , False ),
    ( 'dst'         , 'Tajima'                              , False ),
    ( 'dxf'         , 'Drawing Interchange File'            , False ),
    ( 'e01'         , 'Encase'                              , False ),
    ( 'ecr'         , 'Encrypted file by eCryptfs'          , False ),
    ( 'eCryptfs'    , 'Encrypted file by eCryptfs'          , False ),
    ( 'edb'         , 'Exchange Database'                   , False ),
    ( 'elf'         , 'Executable and Linking Format'       , False ),
    ( 'emb'         , 'Wilcom ES Software'                  , False ),
    ( 'emka'        , 'EMKA IOX data'                       , False ),
    ( 'emlx'        , 'Mac OSX mail format'                 , False ),
    ( 'eps'         , 'Encasulated PostScript'              , False ),
    ( 'ess'         , 'Skyrim Savegame'                     , False ),
    ( 'evt'         , 'Windows registry Event Log'          , False ),
    ( 'evtx'        , 'Microsoft Event Log'                 , False ),
    ( 'exe'         , 'Microsoft executable (PE)'           , False ),
    ( 'fbf'         , 'SymBackup'                           , False ),
    ( 'fbk'         , 'Microsoft Dynamics NAV'              , False ),
    ( 'fcs'         , 'Flow Cytometry Standard 3.0'         , False ),
    ( 'fdb'         , 'Microsoft Dynamics NAV'              , False ),
    ( 'fds'         , 'fwNES Disk Image (with header)'      , False ),
    ( 'f'           , 'Fortran'                             , False ),
    ( 'fh1'         , 'Macromedia Freehand 10'              , False ),
    ( 'fit'         , 'Garmin track file'                   , False ),
    ( 'fits'        , 'NASA Flexible Image Transport'       , False ),
    ( 'fm'          , 'Football Manager'                    , False ),
    ( 'fob'         , 'Microsoft Dynamics NAV'              , False ),
    ( 'fos'         , 'Fallout 4 Savegame'                  , False ),
    ( 'fp5'         , 'File Maker Pro'                      , False ),
    ( 'freeway'     , 'Freeway 5 Pro'                       , False ),
    ( 'frm'         , 'MySQL table definition'              , False ),
    ( 'frm'         , 'Pro/ENGINEER Drawing Form'           , False ),
    ( 'fst'         , 'QuickBook'                           , False ),
    ( 'fs'          , 'Zope data'                           , False ),
    ( 'fwd'         , 'FRWD Sports Computer'                , False ),
    ( 'gam'         , 'Games Factory'                       , False ),
    ( 'gcs'         , 'GCstart'                             , False ),
    ( 'gct'         , 'XFI Fuel Injection Systems'          , False ),
    ( 'gho'         , 'Ghost image file'                    , False ),
    ( 'gm6'         , 'Game Maker 6.0-6.1'                  , False ),
    ( 'gm81'        , 'Game Maker 8.1'                      , False ),
    ( 'gmd'         , 'Game Maker 4.3-5.3A'                 , False ),
    ( 'gmk'         , 'Game Maker 7.0-8.0'                  , False ),
    ( 'gp2'         , 'Gobe Productive Document'            , False ),
    ( 'gpg'         , 'GPG/OpenPGP'                         , False ),
    ( 'gsb'         , 'Grisbi - Personal Finance Manager'   , False ),
    ( 'h'           , 'C header'                            , False ),
    ( 'hdf'         , 'Hierarchical Data Format 4'          , False ),
    ( 'hdr'         , 'ENVI'                                , False ),
    ( 'hds'         , 'Parallels disk image'                , False ),
    ( 'hm'          , 'HyperMesh, structural analysis'      , False ),
    ( 'hr9'         , 'Heredis - Genealogy'                 , False ),
    ( 'html'        , '.gz compressed HTML'                 , False ),
    ( 'html'        , 'HTML'                                , False ),
    ( 'http'        , 'HTTP Cache'                          , False ),
    ( 'ibd'         , 'InnoDB database file'                , False ),
    ( 'ics'         , 'vcalendar'                           , False ),
    ( 'imb'         , 'Incredimail'                         , False ),
    ( 'img'         , 'Filevault'                           , False ),
    ( 'imm'         , 'Incredimail'                         , False ),
    ( 'inf'         , 'Windows Autorun'                     , False ),
    ( 'ini'         , 'Windows .ini'                        , False ),
    ( 'jad'         , 'Java Application Descriptor'         , False ),
    ( 'jar'         , 'Java Archive'                        , False ),
    ( 'jks'         , 'Java Keystore'                       , False ),
    ( 'jnb'         , 'SigmaPlot'                           , False ),
    ( 'jp2'         , 'sample'                              , False ),
    ( 'json'        , 'JavaScript Object Notation'          , False ),
    ( 'jsonlz4'     , 'Mozilla bookmarks'                   , False ),
    ( 'jsp'         , 'JSP script'                          , False ),
    ( 'kdb'         , 'KeePassX'                            , False ),
    ( 'kdbx'        , 'KeePassX'                            , False ),
    ( 'key'         , 'Synology AES key'                    , False ),
    ( 'kmz'         , 'Google Earth KML zipped'             , False ),
    ( 'ldf'         , 'Microsoft SQL Server Log Data'       , False ),
    ( 'ldif'        , 'LDAP Data Interchange Format'        , False ),
    ( 'lit'         , 'Microsoft ITOL/ITLS'                 , False ),
    ( 'lnk'         , 'Microsoft Windows Link (shortcut)'   , False ),
    ( 'lso'         , 'Logic Platinum File'                 , False ),
    ( 'luks'        , 'LUKS encrypted file'                 , False ),
    ( 'lwo'         , '3d model'                            , False ),
    ( 'lxo'         , 'lxo/lwo 3d model'                    , False ),
    ( 'ly'          , 'LilyPond'                            , False ),
    ( 'mat'         , 'Mathlab'                             , False ),
    ( 'mcd'         , 'VectorWorks'                         , False ),
    ( 'mdf'         , 'Microsoft SQL Server Master db'      , False ),
    ( 'mdl'         , 'Mathlab Model'                       , False ),
    ( 'mem'         , 'Mnemosyne Data Base'                 , False ),
    ( 'mfg'         , 'Pro/ENGINEER Manufacturing'          , False ),
    ( 'mig'         , 'Windows Migration Backup'            , False ),
    ( 'mk5'         , 'Custom CAD-CAM'                      , False ),
    ( 'mmap'        , 'MindManager'                         , False ),
    ( 'mny'         , 'MS Money'                            , False ),
    ( 'mobi'        , 'Mobi e-book'                         , False ),
    ( 'msa'         , 'Mensura'                             , False ),
    ( 'msf'         , 'Mozilla "mork database"'             , False ),
    ( 'msg'         , 'Outlook'                             , False ),
    ( 'mxf'         , 'Material Exchange Format'            , False ),
    ( 'MYI'         , 'MySQL MISAM compressed data'         , False ),
    ( 'myo'         , 'Mind Your Own Business'              , False ),
    ( 'nd2'         , 'NIS-Elements'                        , False ),
    ( 'nds'         , 'Nintendo DS Game ROM Image'          , False ),
    ( 'nes'         , 'iNES/iNES 2.0 ROM image'             , False ),
    ( 'nk2'         , 'Outlook Nickfile'                    , False ),
    ( 'notebook'    , 'SMART Notebook'                      , False ),
    ( 'nsf'         , 'Lotus Notes'                         , False ),
    ( 'p65'         , 'Page Maker'                          , False ),
    ( 'paf'         , 'Personal Ancestral File'             , False ),
    ( 'pcap'        , 'tcpdump capture file'                , False ),
    ( 'pcb'         , 'PCB Wizard'                          , False ),
    ( 'pcp'         , 'pcap capture low-endian header'      , False ),
    ( 'pdb'         , 'Protein Data Bank data'              , False ),
    ( 'pdf'         , 'Portable Document Format'            , False ),
    ( 'pds'         , 'Reson - Sonar Data'                  , False ),
    ( 'pf'          , 'Windows prefetch file'               , False ),
    ( 'pfx'         , 'files holding PKCS#12 keys'          , False ),
    ( 'pgp'         , 'OpenPGP/GnuPG encrypted data'        , False ),
    ( 'php'         , 'PHP script'                          , False ),
    ( 'pli'         , 'Mac OS X property list'              , False ),
    ( 'plist'       , 'Apple plist'                         , False ),
    ( 'pl'          , 'Perl script'                         , False ),
    ( 'plt'         , 'Gerber Graphix Advantage'            , False ),
    ( 'pm'          , 'Perl module'                         , False ),
    ( 'ppk'         , 'Putty Public Key'                    , False ),
    ( 'prc'         , 'PalmOS application'                  , False ),
    ( 'prd'         , 'Paessler PRTG'                       , False ),
    ( 'priv'        , 'PGP private key'                     , False ),
    ( 'prt'         , 'Pro/ENGINEER Model'                  , False ),
    ( 'psmodel'     , 'Delcam PowerSHAPE'                   , False ),
    ( 'ps'          , 'PostScript document'                 , False ),
    ( 'pst'         , 'Outlook'                             , False ),
    ( 'ptf'         , 'Pro Tools session File'              , False ),
    ( 'ptx'         , 'Pro Tools session File'              , False ),
    ( 'pub'         , 'SSH DSA/RSA public key'              , False ),
    ( 'pub'         , 'PGP public key'                      , False ),
    ( 'pyc'         , 'Python Compiled Script'              , False ),
    ( 'py'          , 'Python script'                       , False ),
    ( 'pzf'         , 'GraphPrism 4'                        , False ),
    ( 'pzh'         , 'Presto'                              , False ),
    ( 'qbb'         , 'Quickbooks'                          , False ),
    ( 'qbmb'        , 'Quickbooks'                          , False ),
    ( 'qbw'         , 'Quickbooks'                          , False ),
    ( 'qdf'         , 'backup qdf-backup'                   , False ),
    ( 'qdf'         , 'Quicken'                             , False ),
    ( 'qgs'         , 'Quantum GIS'                         , False ),
    ( 'rb'          , 'Ruby'                                , False ),
    ( 'RData'       , 'R Data'                              , False ),
    ( 'reg'         , 'Windows registry config file'        , False ),
    ( 'res'         , 'Microsoft Visual Studio Resource'    , False ),
    ( 'rfp'         , 'Roboform'                            , False ),
    ( 'rlv'         , 'Revelation password'                 , False ),
    ( 'rsa'         , 'SSH RSA private key'                 , False ),
    ( 'rvt'         , 'Revit'                               , False ),
    ( 'save'        , 'Assassins Creed II backup'           , False ),
    ( 'schematic'   , 'Minecraft Schematic File'            , False ),
    ( 'sgcta'       , 'Ciel'                                , False ),
    ( 'sh3d'        , 'Sweet Home 3D'                       , False ),
    ( 'sh'          , 'Shell script'                        , False ),
    ( 'skp'         , 'SketchUp'                            , False ),
    ( 'sla'         , 'Scribus'                             , False ),
    ( 'sldprt'      , 'SolidWorks'                          , False ),
    ( 'sld'         , 'SolidWorks'                          , False ),
    ( 'snag'        , 'Snagit'                              , False ),
    ( 'sp3'         , 'Sisporto SP3/SPM'                    , False ),
    ( 'sparseimage' , 'Filevault'                           , False ),
    ( 'spe'         , 'WinSpec'                             , False ),
    ( 'spf'         , 'ShadowProtect'                       , False ),
    ( 'sqlite'      , 'SQLite databases'                    , False ),
    ( 'sql'         , 'MySQL/phpMyAdmin/PostgreSQL dump'    , False ),
    ( 'sqm'         , 'Windows Live Messenger Log File'     , False ),
    ( 'steuer2014'  , 'Steuer 2014'                         , False ),
    ( 'steuer2015'  , 'Steuer 2015'                         , False ),
    ( 'stl'         , 'Stereolithography CAD'               , False ),
    ( 'stp'         , 'STEP data'                           , False ),
    ( 'studio'      , 'Silhouette Cameo cutting machine'    , False ),
    ( 'tax'         , 'Turbo Tax'                           , False ),
    ( 'tcw'         , 'TurboCAD for Windows'                , False ),
    ( 'tib'         , 'Acronis True Imag'                   , False ),
    ( 'ticket'      , '.bin DINO'                           , False ),
    ( 'torrent'     , 'Torrent data file'                   , False ),
    ( 'tph'         , 'Pro/ENGINEER ToolPath'               , False ),
    ( 'ttd'         , 'TinyTag Data'                        , False ),
    ( 'ttf'         , 'TrueType Font'                       , False ),
    ( 'tz'          , 'Timezone info'                       , False ),
    ( 'url'         , 'Windows URL / Internet Shortcut'     , False ),
    ( 'v2i'         , 'v2i backup'                          , False ),
    ( 'vault'       ,  'McAfee Anti-Theft/FileVault'        , False ),
    ( 'vb'          , 'Microsoft Visual Basic'              , False ),
    ( 'vcf'         , 'VCard'                               , False ),
    ( 'vdi'         , 'Virtual desktop infrastructure'      , False ),
    ( 'veg'         , 'Sony Vegas'                          , False ),
    ( 'vfb'         , 'FontLab'                             , False ),
    ( 'vib'         , 'Veeam Incremental Backup'            , False ),
    ( 'wallet'      , 'Armory bitcoin wallet'               , False ),
    ( 'vmdk'        , 'Vmware'                              , False ),
    ( 'vmg'         , 'Nokia Text Message'                  , False ),
    ( 'wab'         , 'Windows Address Book'                , False ),
    ( 'wim'         , 'Windows imaging (WIM) image'         , False ),
    ( 'win'         , 'Opera preferences'                   , False ),
    ( 'wld'         , 'Terraria world'                      , False ),
    ( 'woff'        , 'Web Open Font Format'                , False ),
    ( 'x4a'         , 'Yamaha-YSFC'                         , False ),
    ( 'x4g'         , 'Yamaha-YSFC'                         , False ),
    ( 'x4p'         , 'Yamaha-YSFC'                         , False ),
    ( 'x4s'         , 'Yamaha-YSFC'                         , False ),
    ( 'xfi'         , 'XFI Electronic Fuel Injection'       , False ),
    ( 'xml'         , '.gz compressed XML'                  , False ),
    ( 'xml'         , 'XML'                                 , False ),
    ( 'xoj'         , 'Xournal'                             , False ),
    ( 'xpi'         , 'Mozilla application'                 , False ),
    ( 'xpt'         , 'Mozilla XPCOM Type Library'          , False ),
    ( 'xsv'         , 'XBOX GTA San Andreas Save File'      , False ),
    ( 'z2d'         , 'ZeroCad'                             , False ),
    ( 'zpr'         , 'ZBrush'                              , False ),
]

DEFAULT_MAIN_WINDOW_SIZE_FACTOR=0.66
DEFAULT_MIN_IMAGE_PIXELS = 639*479  #TODO: implement in filters
DEFAULT_DRAG_ICON_SIZE=128
DEFAULT_DRAG_ICON_OPACITY=0.5
DEFAULT_MAX_SCREEN_HEIGHT=2048
DEFAULT_MAX_SCREEN_HEIGHT=4096
DEFAULT_DEST_BUTTON_WIDTH=200
DEFAULT_DEST_BUTTON_HEIGHT=32
DEFAULT_DEST_BUTTON_ROWS=16
DEFAULT_DEST_BUTTON_COLS=3
DEFAULT_APP_NAME = "PhotoRec Sort"
DEFAULT_ORG_NAME = "Bithead Technology"
DEFAULT_ORG_DOMAIN = "bitheadtech.com"

DEFAULT_LOGGING_LEVEL=logging.INFO
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))

def getTrashBasePath() -> str:
    return f'/home/{os.getlogin()}/.local/share/Trash'

def getTrashFilesPath() -> str:
    return f'{getTrashBasePath()}/files'

def getTrashInfoPath() -> str:
    #return DEFAULT_TRASH_INFO_PATH
    return f'{getTrashBasePath()}/info'

class FatalError(Exception):
    def __init__(self, message="Unspecified error"):
        self.message = message
        super().__init__(self.message)
        self.doDialog()

    def __str__(self):
        return f'{self.message}'

    def doDialog(self):
        QMessageBox.critical(QApplication.desktop(), 
        DEFAULT_APP_NAME,
        f'Fatal error\n\n{self.message}', 
        QMessageBox.Ok)
