#!/usr/bin/python

import os
import logging

USER = os.getlogin() 

# This defines the default path to the top dir of a tree 
# containing "source" files. These files are scanned into a list
# so the user can browse them and copy to "destination" dirs.
DEFAULT_SRC_FILES_PATH = str('/media/'+USER+'/c8f652a8-72b3-4877-88ef-7710a646841d/recovered-test')
#print('DEFAULT_SRC_FILES_PATH:',DEFAULT_SRC_FILES_PATH)
# This defines the default path to a dir (outside of the "source" file 
# tree), which contains one level of subdirs. These subdirs are the 
# "destination" for copy/move operations from "source" files. 
DEFAULT_DST_FILES_PATH = str('/media/'+USER+'/c8f652a8-72b3-4877-88ef-7710a646841d/pics')
#print('DEFAULT_DST_FILES_PATH:',DEFAULT_DST_FILES_PATH)
DEFAULT_MIN_IMAGE_PIXELS = 100*100

DEFAULT_SUPPORTED_IMAGE_FORMATS = {
    #format     #mime type
    'BMP',      #image/bmp
    'BUFR',    
    'DDS',     
    'DIB',      #image/bmp
    'EPS',      #application/postscript
    'FITS',    
    'GIF',      #image/gif
    'GRIB',    
    'HDF5',    
    'ICNS',     #image/icns
    'ICO',      #image/x-icon
    'IM',      
    'JPEG',     #image/jpeg
    'JPEG2000', #image/jp2
    'MPEG',     #video/mpeg
    'MSP',     
    'PCX',      #image/x-pcx
    'PNG',      #image/png
    'PPM',      #image/x-portable-anymap
    'SGI',      #image/sgi
    'SPIDER',      
    'TGA',      #image/x-tga
    'TIFF',     #image/tiff
    'WEBP',     #image/webp
    'WMF',     
    'XBM',      #image/xbm
}

DEFAULT_SUPPORTED_FILE_EXTENSIONS = [
    #ext        #description            #
#Archive
    ( '7z',      '7-Zip archive file'               ),
    ( 'a',       'Unix/Linux archive'               ),
    ( 'ace',     'ACE Archive'                      ),
    ( 'apk',     'Android Package Kit'              ),
    ( 'arj',     'Archive'                          ),
    ( 'bkf',     'MS Backup file'                   ),
    ( 'bz2',     'bzip2 compressed data'            ),
    ( 'cab',     'MS cabinet archive'               ),
    ( 'dar',     'dar3 archive'                     ),
    ( 'deb',     'Debian Archive'                   ),
    ( 'dump',    'Dump/Restore Archive'             ),
    ( 'ghx',     'Grasshopper archive'              ),
    ( 'gz',      'gzip compressed data'             ),
    ( 'lzh',     'lzh/LArc archive'                 ),
    ( 'lzo',     'LZO archive'                      ),
    ( 'par2',    'archive'                          ),
    ( 'rar',     'Rar archive'                      ),
    ( 'rpm',     'RPM package'                      ),
    ( 'stu',     'StuffIt Archive'                  ),
    ( 'tar',     'tar archive'                      ),
    ( 'tar.gz',  'compressed tar archive'           ),
    ( 'vbm',     'Veeam Backup Metadata'            ),
    ( 'wim',     'Windows imaging (WIM) image'      ),
    ( 'xar',     'xar archive'                      ),
    ( 'xz',      'xz Archive'                       ),
    ( 'zip',     'zip archive'                      ),
    #Multimedia     
    ( '3ds',    'max'                               ),        
    ( '3dm',    'Rhino / openNURBS'                 ),
    ( '3g2',    'Video for 3G mobile phone (CDMA)'  ),
    ( '3gp',    'Video for 3G mobile phone (GSM)'   ),
    ( 'abr',    'Adobe Brush'                       ),
    ( 'acb',    'Adobe Color Book'                  ),
    ( 'ado',    'Adobe Duotone Options'             ),
    ( 'aep',    'After Effects'                     ),
    ( 'afdesign', 'afdesign'                        ),
    ( 'aif',    'Apple Audio'                       ),
    ( 'albm',   'HP Photosmart Photo Printing Album'),
    ( 'all',    'Cubase Song format'                ),
    ( 'als',    'Ableton Live Sets'                 ),
    ( 'ani',    'Windows Animated Cursor'           ),
    ( 'ape',    'Monkey Audio compressed format'    ),
    ( 'ari',    'ARRI Raw Video'                    ),
    ( 'arw',    'Sony raw image (TIFF image)'       ),
    ( 'asf',    'Advanced Streaming Format'         ),
    ( 'wma',    'Windows Media Audio'               ),
    ( 'wmv',    'Windows Media Video'               ),
    ( 'asl',    'Adobe Layer Style'                 ),
    ( 'au',     'Sun/NeXT audio data'               ),
    ( 'avi',    'RIFF video'                        ),
    ( 'axp',    'Pinnacle Studio'                   ),
    ( 'binvox', 'Binvox Voxel File'                 ),
    ( 'bdm',    'AVHCD index'                       ),
    ( 'bld',    'blender'                           ),
    ( 'blend',  'Blender'                           ),
    ( 'bmp',    'BMP bitmap image'                  ),
    ( 'bpg',    'Better Portable Graphics image'    ),
    ( 'bvr',    'Blue Iris DVR'                     ),
    ( 'c4d',    'Cinema 4d'                         ),
    ( 'caf',    'Core Audio Format'                 ),
    ( 'cam',    'Image'                             ),
    ( 'camrec', 'Camtasia Camrec'                   ),
    ( 'CATDrawing', 'CATIA'                         ),
    ( 'cda',    'CD Audio'                          ),
    ( 'cdd',    'Concept Draw Document'             ),
    ( 'cdl',    'Concept Draw Library'              ),
    ( 'cdr',    'Corel Draw (RIFF)'                 ),
    ( 'cdt',    'Concept Draw Template'             ),
    ( 'celtx',  'Celtx'                             ),
    ( 'che',    'Compucon EOS Design File'          ),
    ( 'comicdoc', 'Comic Life'                      ),
    ( 'cpi',    'AVCHD Clip Information'            ),
    ( 'cpr',    'Cubase Project File'               ),
    ( 'cr2',    'Canon Raw 2 picture (TIFF image)'  ),
    ( 'cr3',    'Canon Raw v3 (MOV family)'         ),
    ( 'crw',    'Canon Raw picture'                 ),
    ( 'csh',    'Adobe Custom shapes'               ),
    ( 'ctg',    'Canon catalog'                     ),
    ( 'cue',    'Cue sheet'                         ),
    ( 'dad',    'Micae DVR'                         ),
    ( 'db',     'Thumbs.db'                         ),
    ( 'dcm',    'DICOM'                             ),
    ( 'dcr',    'Kodak Raw picture (TIFF image)'    ),
    ( 'djv',    'DjVu'                              ),
    ( 'dng',    'Adobe Digital Negative'            ),
    ( 'dp',     'Photobook Designer Software'       ),
    ( 'dpx',    'Cineon image file/SMTPE DPX'       ),
    ( 'ds2',    'Digital Speech Standard v2'        ),
    ( 'dsc',    'Nikon DSC'                         ),
    ( 'dss',    'Digital Speech Standard'           ),
    ( 'ds_store', 'Apple indexing file'             ),
    ( 'dta',    'SPSS'                              ),
    ( 'dv',     'DIF Digital Video'                 ),
    ( 'dvi',    'TeX DVI'                           ),
    ( 'dvr',    'RT60'                              ),
    ( 'dwg',    'AutoCAD'                           ),
    ( 'emf',    'Windows Enhanced MetaFile'         ),
    ( 'epub',   'Electronic Publication'            ),
    ( 'ers',    'ER Mapper Rasters'                 ),
    ( 'exs',    'Apple Logic'                       ),
    ( 'fcp',    'Final Cut Pro'                     ),
    ( 'fh10',   'Macromedia Freehand 10'            ),
    ( 'fh5',    'Macromedia Freehand 5'             ),
    ( 'flac',   'Free Lossless Audio Codec'         ),
    ( 'fla',    'Flash Project File'                ),
    ( 'flp',    'Fruity Loop'                       ),
    ( 'flv',    'Macromedia'                        ),
    ( 'gi',     'Roxio Creator'                     ),
    ( 'gif',    'Graphic Interchange Format'        ),
    ( 'gp4',    'Guitar Pro 4'                      ),
    ( 'gp5',    'Guitar Pro 5'                      ),
    ( 'gpx',    'Guitar Pro 6'                      ),
    ( 'gsm',    'Group Speciale Mobile GSM 06.10'   ),
    ( 'heic',   'High Efficiency Image File'        ),
    ( 'icc',    'Color profiles'                    ),
    ( 'icns',   'Apple Icon Image'                  ),
    ( 'ico',    'Windows Icon'                      ),
    ( 'idf',    'MIDI Instruments Definition File'  ),
    ( 'idx',    'RT60'                              ),
    ( 'iff',    'Audio Interchange File Format'     ),
    ( 'ind',    'InDesign File'                     ),
    ( 'ifo',    'DVD Video manager or title set'    ),
    ( 'indd',   'Macromedia InDesign'               ),
    ( 'info',   'ZoomBrowser Thumbnail info'        ),
    ( 'ipt',    'Autodesk Inventor part file'       ),
    ( 'iso',    'CD/DVD iso image (ISO0660)'        ),
    ( 'it',     'Impulse Tracker'                   ),
    ( 'itu',    'iTunes'                            ),
    ( 'ora',    'Mypaint .ora'                      ),
    ( 'jng',    'JPEG Network Graphics'             ),
    ( 'jpg',    'JPEG 2000'                         ),
    ( 'jpg',    'JPEG picture'                      ),
    ( 'kra',    'Krita'                             ),
    ( 'logic',  'Apple Logic Studio'                ),
    ( 'm2t',    'Blu-ray MPEG-2'                    ),
    ( 'm2ts',   'Blu-ray MPEG-2'                    ),
    ( 'm3u',    'MPEG Audio Layer 3 URL'            ),
    ( 'm4p',    'MPEG-4 Audio'                      ),
    ( 'max',    '3ds'                               ),
    ( 'max',    'Paperport'                         ),
    ( 'mb',     'Maya'                              ),
    ( 'mcf',    'Fotobook'                          ),
    ( 'mfa',    'Games Factory Multimedia Fusion'   ),
    ( 'mhbd',   'iTunes'                            ),
    ( 'mid',    'MIDI'                              ),
    ( 'mkv',    'Matroska'                          ),
    ( 'mlv',    'Magic Lantern Video'               ),
    ( 'mng',    'Multiple-Image Network Graphics'   ),
    ( 'mov',    'Quicktime Movie'                   ),
    ( 'mp',     'Maya'                              ),
    ( 'mp3',    'MPEG ADTS, layer III, v1 audio'    ),
    ( 'mp4',    'MPEG 4'                            ),
    ( 'mpg',    'MPEG video'                        ),
    ( 'mpl',    'AVHCD playlist'                    ),
    ( 'mpo',    'Multi-picture format'              ),
    ( 'mrw',    'Minolta Raw picture'               ),
    ( 'mus',    'Finale Music Score'                ),
    ( 'mws',    'MetaStock'                         ),
    ( 'nef',    'Nikon Raw picture (TIFF image)'    ),
    ( 'oci',    'OpenCanvas Image .oci'             ),
    ( 'ogg',    'OGG Vorbis audio'                  ),
    ( 'ogm',    'OGG audio'                         ),
    ( 'ogv',    'Ogg data, Theora video'            ),
    ( 'orf',    'Olympus Raw Format picture'        ),
    ( 'pbm',    'Portable Bitmap'                   ),
    ( 'pct',    'Macintosh Picture'                 ),
    ( 'pcx',    'PCX file format'                   ),
    ( 'psb',    'Adobe Photoshop Image'             ),
    ( 'pef',    'Pentax Raw picture (TIFF image)'   ),
    ( 'pgm',    'Portable GrayMap'                  ),
    ( 'png',    'Portable Network Graphics'         ),
    ( 'pnm',    'Portable anymap'                   ),
    ( 'ppm',    'Portable PixMap'                   ),
    ( 'prproj', 'Adobe Premiere project'            ),
    ( 'psd',    'Adobe Photoshop Image'             ),
    ( 'psf',    'Print Shop File'                   ),
    ( 'psp',    'Paint Shop Pro Image File'         ),
    ( 'ptb',    'PowerTab'                          ),
    ( 'pts',    'PTGui panoramic stitching'         ),
    ( 'pvp',    'Php Video Pro'                     ),
    ( 'qcp',    'QCP Speech Data (RFC3625)'         ),
    ( 'qkt',    'Apple QuickTake 100'               ),
    ( 'qxd',    'QuarkXpress Document'              ),
    ( 'qxp',    'QuarkXpress Document'              ),
    ( 'r3d',    'RED r3d camera'                    ),
    ( 'raf',    'Raw Fujifilm picture'              ),
    ( 'ram',    'Real Media'                        ),
    ( 'ra',     'Real Audio'                        ),
    ( 'raw',    'Contax/Panasonic/Leica picture'    ),
    ( 'rdc',    'Rollei picture'                    ),
    ( 'rm',     'Real Media'                        ),
    ( 'rns',    'Reason'                            ),
    ( 'rns',    'Reason Audio File'                 ),
    ( 'rpp',    'Reaper Project'                    ),
    ( 'rw2',    'Panasonic Raw 2'                   ),
    ( 'rx2',    'Zotope RX 2, Audio Repair file'    ),
    ( 'ses',    'Cool Edit/Adobe Audition session'  ),
    ( 'shn',    'Shorten audio file'                ),
    ( 'sib',    'Sibelius'                          ),
    ( 'sit',    'Mikron'                            ),
    ( 'skd',    'AutoSketch drawing'                ),
    ( 'sketch', 'Vector graphics file by Sketch'    ),
    ( 'smil',   'Synchronized Multimedia Integration Language' ),
    ( 'spss',   'SPSS'                              ),
    ( 'sr2',    'Sony Raw picture (TIFF image)'     ),
    ( 'svg',    'Scalable Vector Graphics'          ),
    ( 'swc',    'Macromedia Compressed Flash'       ),
    ( 'swf',    'MacroMedia Flash (Compiled)'       ),
    ( 'tg',     'Tux Guitar 1.2'                    ),
    ( 'tif',    'Tag Image File Format'             ),
    ( 'TiVo',   'video record'                      ),
    ( 'tod',    'Blu-ray MPEG-2'                    ),
    ( 'tpl',    'Adobe Tool Preset'                 ),
    ( 'ts',     'MPEG-2 Transport Stream'           ),
    ( 'vdj',    'VirtualDJ'                         ),
    ( 'wav',    'RIFF audio'                        ),
    ( 'wdp',    'JPEG XR'                           ),
    ( 'webm',   'Matroska'                          ),
    ( 'webp',   'WebP Image Format'                 ),
    ( 'wee',    'weecast'                           ),
    ( 'wmf',    'Windows Metafile'                  ),
    ( 'wnk',    'Wink screen capture'               ),
    ( 'wpb',    'OpenCanvas files'                  ),
    ( 'wpl',    'Windows Play List'                 ),
    ( 'wtv',    'Windows Media Center TV'           ),
    ( 'wv',     'WavPack Compressor'                ),
    ( 'x3f',    'Sigma/Foveon X3 raw picture'       ),
    ( 'x3i',    'Sigma/Foveon X3 raw picture'       ),
    ( 'xcf',    'GIMP XCF File'                     ),
    ( 'xd',     'Adobe xd'                          ),
    ( 'xm',     'FastTrackerII Extended Module'     ),
    ( 'xmp',    'Adobe Extensible Metadata Platform' ),
    ( 'xrns',   'Extended Renoise song file'        ),
    ( 'xv',     'XV thumbnail image'                ),
    ( 'zcode',  'Zortrax 3D printing'               ),
    #Office
    ('accdb',   'Microsoft Access database'         ),
    ('ai',      'Adobe Illustrator'                 ),
    ('apr',     'Lotus Approach'                    ),
    ('csv',     'Comma separated values'            ),
    ('cwk',     'AppleWorks'                        ),
    ('doc',     'Microsoft Word (OLE document)'     ),
    ('docx',    'Microsoft Office OpenXML (ZIP)'    ),
    ('et',      'Microsoft Excel'                   ),
    ('fb2',     'FictionBook'                       ),
    ('fods',    'OpenDocument Flat XML Spreadsheet' ),
    ('fp7',     'File Maker Pro 7'                  ),
    ('fp12',    'File Maker Pro 12'                 ),
    ('gnucash', 'GnuCash,'                          ),
    ('kmy',     'KMyMoney (gz file family)'         ),
    ('lyx',     'LyX'                               ),
    ('mdb',     'Microsoft Access database'         ),
    ('njx',     'NJStar'                            ),
    ('odg',     'OpenDocument Graphics (ZIP)'       ),
    ('odp',     'OpenDocument Presentation (ZIP)'   ),
    ('ods',     'OpenDocument Spreadsheet (ZIP)'    ),
    ('odt',     'OpenDocument Text (ZIP)'           ),
    ('one',     'Microsoft OneNote'                 ),
    ('pages',   'iWork'                             ),
    ('pap',     'Papyrus word file'                 ),
    ('ppt',     'PowerPoint presentation'           ),
    ('pptx',    'Microsoft Office "Open" XML (ZIP)' ),
    ('pub',     'Microsoft Publisher'               ),
    ('qbb',     'Quickbooks Backup'                 ),
    ('qbw',     'Quickbooks - Company File'         ),
    ('qpw',     'Quattro Pro spreadsheet'           ),
    ('rtf',     'Rich Text Format'                  ),
    ('sda',     'StarDraw (OLE document)'           ),
    ('sdc',     'StarCalc (OLE document)'           ),
    ('sdd',     'StarImpress (OLE document)'        ),
    ('sdw',     'StarWriter (OLE document)'         ),
    ('slk',     'Sylk, Multiplan Symbolic Link'     ),
    ('sav',     'SPSS saved data'                   ),
    ('snt',     'Windows Sticky Notes'              ),
    ('sxc',     'OpenOffice Spreadsheet (ZIP)'      ),
    ('sxd',     'OpenOffice Drawing (ZIP)'          ),
    ('sxi',     'OpenOffice Presentation (ZIP)'     ),
    ('sxw',     'OpenOffice Text Document (ZIP)'    ),
    ('tex',     'LaTeX (Text file family)'          ),
    ('txt',     'Text file'                         ),
    ('vsd',     'Visio document (OLE document)'     ),
    ('vsdx',    'Microsoft Visio 2010+'             ),
    ('wpd',     'Corel Documents'                   ),
    ('wps',     'Microsoft Works (Ole document'     ),
    ('xlr',     'Microsoft Works Spreadsheet/Chart' ),
    ('xls',     'Microsoft Excel'                   ),
    ('xlsx',    'Microsoft Office OpenXML'          ),
    ('wdb',     'Microsoft Works Database'          ),
    ('wk4',     'Lotus 1-2-3 v4'                    ),
    ('wks',     'Lotus 1-2-3 v5'                    ),
    #Others
    ( '1cd',    'Russian Finance 1C:Enterprise 8'   ),
    ( 'ab',     'Mac Address Book'                  ),
    ( 'adr',    'Opera Hotlist'                     ),
    ( 'agn',    'Autogen'                           ),
    ( 'ahn',    'Ahnenblatt'                        ),
    ( 'amb',    'Licom AlphaCAM'                    ),
    ( 'amd',    'AlphaCAM'                          ),
    ( 'amr',    'Adaptive Multi-Rate'               ),
    ( 'amt',    'AlphaCAM'                          ),
    ( 'apa',    'APA Style Helper'                  ),
    ( 'apple',  'AppleSingle/AppleDouble'           ),
    ( 'asm',    'Pro/ENGINEER Assembly'             ),
    ( 'asp',    'ASP script'                        ),
    ( 'atd',    'Agelong Tree Database'             ),
    ( 'atd',    'AlphaCAM'                          ),
    ( 'att',    'AlphaCAM'                          ),
    ( 'axx',    'AxCrypt'                           ),
    ( 'bac',    'Bacula backup'                     ),
    ( 'bai',    'SAM/BAM sequencing file formats'   ),
    ( 'bam',    'SAM/BAM sequencing file formats'   ),
    ( 'bat',    'Dos/Windows Batch'                 ),
    ( 'bgz',    'SAM/BAM sequencing file formats'   ),
    ( 'bim',    'Broadcast Interface Module'        ),
    ( 'c',      'C programming language'            ),
    ( 'chm',    'Microsoft Windows HtmlHelp Data'   ),
    ( 'class',  'Java Class'                        ),
    ( 'cls',    'Microsoft VB'                      ),
    ( 'cm',     'Comic Life'                        ),
    ( 'compress', 'MS compress file (SZDD)'         ),
    ( 'cow',    'Qemu Image'                        ),
    ( 'cp_',    'MS compress file (SZDD)'           ),
    ( 'csi',    'SAM/BAM sequencing file formats'   ),
    ( 'd2s',    'Diablo II'                         ),
    ( 'dat',    'Internet Explorer index.dat'       ),
    ( 'dbf',    'DBase 3 (prone to false positive)' ),
    ( 'dbn',    'DriftBox'                          ),
    ( 'dbx',    'Outlook Express'                   ),
    ( 'dc',     'TSCe Survey Controller DC v10.0'   ),
    ( 'ddf',    'Didson Data File (v3 and v4)'      ),
    ( 'dex',    'Dalvik'                            ),
    ( 'dgn',    'MicroStation CAD file format'      ),
    ( 'dif',    'Lotus Data Interchange Format'     ),
    ( 'dim',    'SunPCI Disk Image'                 ),
    ( 'diskimage',  'SunPCI Disk Image'             ),
    ( 'dll',    'Microsoft Dynamic Link Library'    ),
    ( 'dmp',    'Oracle Dump (export)'              ),
    ( 'drw',    'Pro/ENGINEER Drawing'              ),
    ( 'dsa',    'SSH DSA private key'               ),
    ( 'dst',    'Tajima'                            ),
    ( 'dxf',    'Drawing Interchange File'          ),
    ( 'e01',    'Encase'                            ),
    ( 'ecr',    'Encrypted file by eCryptfs'        ),
    ( 'eCryptfs', 'Encrypted file by eCryptfs'      ),
    ( 'edb',    'Exchange Database'                 ),
    ( 'elf',    'Executable and Linking Format'     ),
    ( 'emb',    'Wilcom ES Software'                ),
    ( 'emka',   'EMKA IOX data'                     ),
    ( 'emlx',   'Mac OSX mail format'               ),
    ( 'eps',    'Encasulated PostScript'            ),
    ( 'ess',    'Skyrim Savegame'                   ),
    ( 'evt',    'Windows registry Event Log'        ),
    ( 'evtx',   'Microsoft Event Log'               ),
    ( 'exe',    'Microsoft executable (PE)'         ),
    ( 'fbf',    'SymBackup'                         ),
    ( 'fbk',    'Microsoft Dynamics NAV'            ),
    ( 'fcs',    'Flow Cytometry Standard 3.0'       ),
    ( 'fdb',    'Microsoft Dynamics NAV'            ),
    ( 'fds',    'fwNES Disk Image (with header)'    ),
    ( 'f',      'Fortran'                           ),
    ( 'fh1',    'Macromedia Freehand 10'            ),
    ( 'fit',    'Garmin track file'                 ),
    ( 'fits',   'NASA Flexible Image Transport'     ),
    ( 'fm',     'Football Manager'                  ),
    ( 'fob',    'Microsoft Dynamics NAV'            ),
    ( 'fos',    'Fallout 4 Savegame'                ),
    ( 'fp5',    'File Maker Pro'                    ),
    ( 'freeway', 'Freeway 5 Pro'                    ),
    ( 'frm',    'MySQL table definition'            ),
    ( 'frm',    'Pro/ENGINEER Drawing Form'         ),
    ( 'fst',    'QuickBook'                         ),
    ( 'fs',     'Zope data'                         ),
    ( 'fwd',    'FRWD Sports Computer'              ),
    ( 'gam',    'Games Factory'                     ),
    ( 'gcs',    'GCstart'                           ),
    ( 'gct',    'XFI Fuel Injection Systems'        ),
    ( 'gho',    'Ghost image file'                  ),
    ( 'gm6',    'Game Maker 6.0-6.1'                ),
    ( 'gm81',   'Game Maker 8.1'                    ),
    ( 'gmd',    'Game Maker 4.3-5.3A'               ),
    ( 'gmk',    'Game Maker 7.0-8.0'                ),
    ( 'gp2',    'Gobe Productive Document'          ),
    ( 'gpg',    'GPG/OpenPGP'                       ),
    ( 'gsb',    'Grisbi - Personal Finance Manager' ),
    ( 'h',      'C header'                          ),
    ( 'hdf',    'Hierarchical Data Format 4'        ),
    ( 'hdr',    'ENVI'                              ),
    ( 'hds',    'Parallels disk image'              ),
    ( 'hm',     'HyperMesh, structural analysis'    ),
    ( 'hr9',    'Heredis - Genealogy'               ),
    ( 'html',   '.gz compressed HTML'                ),
    ( 'html',   'HTML'                              ),
    ( 'http',   'HTTP Cache'                        ),
    ( 'ibd',    'InnoDB database file'              ),
    ( 'ics',    'vcalendar'                         ),
    ( 'imb',    'Incredimail'                       ),
    ( 'img',    'Filevault'                         ),
    ( 'imm',    'Incredimail'                       ),
    ( 'inf',    'Windows Autorun'                   ),
    ( 'ini',    'Windows .ini'                      ),
    ( 'jad',    'Java Application Descriptor'       ),
    ( 'jar',    'Java Archive'                      ),
    ( 'jks',    'Java Keystore'                     ),
    ( 'jnb',    'SigmaPlot'                         ),
    ( 'jp2',    'sample'                            ),
    ( 'json',   'JavaScript Object Notation'        ),
    ( 'jsonlz4',    'Mozilla bookmarks'             ),
    ( 'jsp',    'JSP script'                        ),
    ( 'kdb',    'KeePassX'                          ),
    ( 'kdbx',   'KeePassX'                          ),
    ( 'key',    'Synology AES key'                  ),
    ( 'kmz',    'Google Earth KML zipped'           ),
    ( 'ldf',    'Microsoft SQL Server Log Data'     ),
    ( 'ldif',   'LDAP Data Interchange Format'      ),
    ( 'lit',    'Microsoft ITOL/ITLS'               ),
    ( 'lnk',    'Microsoft Windows Link (shortcut)' ),
    ( 'lso',    'Logic Platinum File'               ),
    ( 'luks',   'LUKS encrypted file'               ),
    ( 'lwo',    '3d model'                          ),
    ( 'lxo',    'lxo/lwo 3d model'                  ),
    ( 'ly',     'LilyPond'                          ),
    ( 'mat',    'Mathlab'                           ),
    ( 'mcd',    'VectorWorks'                       ),
    ( 'mdf',    'Microsoft SQL Server Master db'    ),
    ( 'mdl',    'Mathlab Model'                     ),
    ( 'mem',    'Mnemosyne Data Base'               ),
    ( 'mfg',    'Pro/ENGINEER Manufacturing'        ),
    ( 'mig',    'Windows Migration Backup'          ),
    ( 'mk5',    'Custom CAD-CAM'                    ),
    ( 'mmap',   'MindManager'                       ),
    ( 'mny',    'MS Money'                          ),
    ( 'mobi',   'Mobi e-book'                       ),
    ( 'msa',    'Mensura'                           ),
    ( 'msf',    'Mozilla "mork database"'           ),
    ( 'msg',    'Outlook'                           ),
    ( 'mxf',    'Material Exchange Format'          ),
    ( 'MYI',    'MySQL MISAM compressed data'       ),
    ( 'myo',    'Mind Your Own Business'            ),
    ( 'nd2',    'NIS-Elements'                      ),
    ( 'nds',    'Nintendo DS Game ROM Image'        ),
    ( 'nes',    'iNES/iNES 2.0 ROM image'           ),
    ( 'nk2',    'Outlook Nickfile'                  ),
    ( 'notebook', 'SMART Notebook'                  ),
    ( 'nsf',    'Lotus Notes'                       ),
    ( 'p65',    'Page Maker'                        ),
    ( 'paf',    'Personal Ancestral File'           ),
    ( 'pcap',   'tcpdump capture file'              ),
    ( 'pcb',    'PCB Wizard'                        ),
    ( 'pcp',    'pcap capture low-endian header'    ),
    ( 'pdb',    'Protein Data Bank data'            ),
    ( 'pdf',    'Portable Document Format'          ),
    ( 'pds',    'Reson - Sonar Data'                ),
    ( 'pf',     'Windows prefetch file'             ),
    ( 'pfx',    'files holding PKCS#12 keys'        ),
    ( 'pgp',    'OpenPGP/GnuPG encrypted data'      ),
    ( 'php',    'PHP script'                        ),
    ( 'pli',    'Mac OS X property list'            ),
    ( 'plist',  'Apple plist'                       ),
    ( 'pl',     'Perl script'                       ),
    ( 'plt',    'Gerber Graphix Advantage'          ),
    ( 'pm',     'Perl module'                       ),
    ( 'ppk',    'Putty Public Key'                  ),
    ( 'prc',    'PalmOS application'                ),
    ( 'prd',    'Paessler PRTG'                     ),
    ( 'priv',   'PGP private key'                   ),
    ( 'prt',    'Pro/ENGINEER Model'                ),
    ( 'psmodel',    'Delcam PowerSHAPE'             ),
    ( 'ps',     'PostScript document'               ),
    ( 'pst',    'Outlook'                           ),
    ( 'ptf',    'Pro Tools session File'            ),
    ( 'ptx',    'Pro Tools session File'            ),
    ( 'pub',    'SSH DSA/RSA public key'            ),
    ( 'pub',    'PGP public key'                    ),
    ( 'pyc',    'Python Compiled Script'            ),
    ( 'py',     'Python script'                     ),
    ( 'pzf',    'GraphPrism 4'                      ),
    ( 'pzh',    'Presto'                            ),
    ( 'qbb',    'Quickbooks'                        ),
    ( 'qbmb',   'Quickbooks'                        ),
    ( 'qbw',    'Quickbooks'                        ),
    ( 'qdf',    'backup qdf-backup'                 ),
    ( 'qdf',    'Quicken'                           ),
    ( 'qgs',    'Quantum GIS'                       ),
    ( 'rb',     'Ruby'                              ),
    ( 'RData',  'R Data'                            ),
    ( 'reg',    'Windows registry config file'      ),
    ( 'res',    'Microsoft Visual Studio Resource'  ),
    ( 'rfp',    'Roboform'                          ),
    ( 'rlv',    'Revelation password'               ),
    ( 'rsa',    'SSH RSA private key'               ),
    ( 'rvt',    'Revit'                             ),
    ( 'save',   'Assassins Creed II backup'         ),
    ( 'schematic',  'Minecraft Schematic File'      ),
    ( 'sgcta',  'Ciel'                              ),
    ( 'sh3d',   'Sweet Home 3D'                     ),
    ( 'sh',     'Shell script'                      ),
    ( 'skp',    'SketchUp'                          ),
    ( 'sla',    'Scribus'                           ),
    ( 'sldprt',     'SolidWorks'                    ),
    ( 'sld',    'SolidWorks'                        ),
    ( 'snag',   'Snagit'                            ),
    ( 'sp3',    'Sisporto SP3/SPM'                  ),
    ( 'sparseimage',    'Filevault'                 ),
    ( 'spe',    'WinSpec'                           ),
    ( 'spf',    'ShadowProtect'                     ),
    ( 'sqlite', 'SQLite databases'                  ),
    ( 'sql',    'MySQL/phpMyAdmin/PostgreSQL dump'  ),
    ( 'sqm',    'Windows Live Messenger Log File'   ),
    ( 'steuer2014', 'Steuer 2014'                   ),
    ( 'steuer2015', 'Steuer 2015'                   ),
    ( 'stl',    'Stereolithography CAD'             ),
    ( 'stp',    'STEP data'                         ),
    ( 'studio', 'Silhouette Cameo cutting machine'  ),
    ( 'tax',    'Turbo Tax'                         ),
    ( 'tcw',    'TurboCAD for Windows'              ),
    ( 'tib',    'Acronis True Imag'                 ),
    ( 'ticket', '.bin DINO'                         ),
    ( 'torrent',    'Torrent data file'             ),
    ( 'tph',    'Pro/ENGINEER ToolPath'             ),
    ( 'ttd',    'TinyTag Data'                      ),
    ( 'ttf',    'TrueType Font'                     ),
    ( 'tz',     'Timezone info'                     ),
    ( 'url',    'Windows URL / Internet Shortcut'   ),
    ( 'v2i',    'v2i backup'                        ),
    ( 'vault',  'McAfee Anti-Theft/FileVault'       ),
    ( 'vb',     'Microsoft Visual Basic'            ),
    ( 'vcf',    'VCard'                             ),
    ( 'vdi',    'Virtual desktop infrastructure'    ),
    ( 'veg',    'Sony Vegas'                        ),
    ( 'vfb',    'FontLab'                           ),
    ( 'vib',    'Veeam Incremental Backup'          ),
    ( 'wallet', 'Armory bitcoin wallet'             ),
    ( 'vmdk',   'Vmware'                            ),
    ( 'vmg',    'Nokia Text Message'                ),
    ( 'wab',    'Windows Address Book'              ),
    ( 'wim',    'Windows imaging (WIM) image'       ),
    ( 'win',    'Opera preferences'                 ),
    ( 'wld',    'Terraria world'                    ),
    ( 'woff',   'Web Open Font Format'              ),
    ( 'x4a',    'Yamaha-YSFC'                       ),
    ( 'x4g',    'Yamaha-YSFC'                       ),
    ( 'x4p',    'Yamaha-YSFC'                       ),
    ( 'x4s',    'Yamaha-YSFC'                       ),
    ( 'xfi',    'XFI Electronic Fuel Injection'     ),
    ( 'xml',    '.gz compressed XML'                ),
    ( 'xml',    'XML'                               ),
    ( 'xoj',    'Xournal'                           ),
    ( 'xpi',    'Mozilla application'               ),
    ( 'xpt',    'Mozilla XPCOM Type Library'        ),
    ( 'xsv',    'XBOX GTA San Andreas Save File'    ),
    ( 'z2d',    'ZeroCad'                           ),
    ( 'zpr',    'ZBrush'                            ),
]

DEFAULT_LOGGING_LEVEL=logging.INFO
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))
